title: Henspace
description: A variety of stuff I'm working on the the moment.
logo: /images/logo.png
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
github:
  is_project_page: false
